spring:
  config:
    # settings for local development environment only
    import: optional:file:application-local.yaml

  cloud:
    function:
      definition: inConsumer
    stream:
      function:
        # require to define functions explicitly
        autodetect: false
      binders:
        kafka-input:
          type: kafka
          environment:
            # https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html#_kafka_binder_properties
            spring.cloud.stream.kafka.binder.brokers: ${app.kafka.bootstrapServersList}
        kafka-output:
          type: kafka
          environment:
            # https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html#_kafka_binder_properties
            spring.cloud.stream.kafka.binder.brokers: ${app.kafka.bootstrapServersList}
      bindings:
        inConsumer-in-0:
          binder: kafka-input
          destination: ${app.kafka.consumer.topic}
          group: ${app.kafka.consumer.group}
        producer-out-0:
          binder: kafka-output
          destination: ${app.kafka.producer.topic}
      kafka:
        bindings:
          inConsumer-in-0:
            #see https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties
            consumer:
              resetOffsets: true
              # see org.springframework.kafka.listener.ContainerProperties.AckMode
              ackMode: BATCH
          producer-out-0:
            producer:
              sync: true
